[package]
name = "china-travel-app"
version = "0.1.0"
authors = ["rdelacrz <roger.delacruz.jr@gmail.com>"]
edition = "2021"

[dependencies]
async-trait = "0.1.89"
axum = { version = "0.8.4", optional = true }
base64 = "0.22.1"
dioxus = { version = "=0.7.10", features = ["router"] }
dioxus-icons = { version = "0.1.0", default-features = false }
dioxus-liveview = { version = "=0.7.10", features = ["axum"], optional = true }
dioxus-primitives = { git = "https://github.com/DioxusLabs/dioxus-components", rev = "bf007c15d0cf4d04d3181cc46cf12325aa773955", version = "0.0.1", default-features = false }
linkify = "0.11.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
thiserror = "2.0.20"
tokio = { version = "1", features = ["fs", "macros", "rt-multi-thread", "time"] }
tokio-rusqlite = { version = "0.7.0", features = ["bundled"] }
tower-http = { version = "0.6", features = ["fs"], optional = true }
url = "2"

[dev-dependencies]
dioxus-ssr = "=0.7.10"
tempfile = "3"

[features]
default = ["mobile"]
mobile = ["dioxus/mobile"]
web = ["dioxus/web"]
liveview = [
    "dioxus/liveview",
    "dep:axum",
    "dep:dioxus-liveview",
    "dep:tower-http",
]
