[application]
title = "China Travel App"
tailwind_input = "tailwind.css"
tailwind_output = "assets/tailwind.css"
android_main_activity = "android/MainActivity.kt"

[web.app]
title = "China Travel App"

[android]
identifier = "com.rdelacruz.chinatravel"
min_sdk = 26
target_sdk = 35
compile_sdk = 35
